#!/usr/bin/env node
/**
 * Build static site from site/products/ only.
 * Each site/products/<slug>/ has images and optional info.json (title, excerpt, content, price, stripePaymentLinkUrl).
 * Output: site/index.html, site/product/*.html, site/css/style.css (images already in site/products/).
 */

import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();
const SITE_DIR = path.join(ROOT, 'site');
const SITE_PRODUCTS_DIR = path.join(SITE_DIR, 'products');
const IMAGE_EXT = /\.(jpg|jpeg|png|gif|webp)$/i;

function getProducts() {
  if (!fs.existsSync(SITE_PRODUCTS_DIR)) return [];
  const dirs = fs.readdirSync(SITE_PRODUCTS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);
  const products = [];
  for (const slug of dirs) {
    const dirPath = path.join(SITE_PRODUCTS_DIR, slug);
    const files = fs.readdirSync(dirPath)
      .filter(f => IMAGE_EXT.test(f))
      .sort();
    const infoPath = path.join(dirPath, 'info.json');
    let meta = { title: slug.replace(/-/g, ' '), excerpt: '', content: '', price: 0, stripePaymentLinkUrl: '' };
    if (fs.existsSync(infoPath)) {
      try {
        meta = { ...meta, ...JSON.parse(fs.readFileSync(infoPath, 'utf8')) };
      } catch (_) {}
    }
    products.push({ slug, images: files, ...meta });
  }
  return products.sort((a, b) => (a.slug || '').localeCompare(b.slug || ''));
}

function escapeHtml(s) {
  if (!s) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function layout(title, body, active = '', base = '') {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)} | Art Supreme</title>
  <link rel="stylesheet" href="${base}css/style.css">
</head>
<body>
  <header class="site-header">
    <a href="${base}index.html" class="logo">Art Supreme</a>
    <nav>
      <a href="${base}index.html"${active === 'home' ? ' class="active"' : ''}>Gallery</a>
      <a href="${base}shipping.html"${active === 'shipping' ? ' class="active"' : ''}>Shipping</a>
      <a href="${base}contact.html"${active === 'contact' ? ' class="active"' : ''}>Contact</a>
    </nav>
  </header>
  <main class="site-main">
    ${body}
  </main>
  <footer class="site-footer">
    <p>&copy; Art Supreme. World's first AI gallery.</p>
  </footer>
</body>
</html>`;
}

function build() {
  const products = getProducts();
  console.log('Products:', products.length);

  fs.mkdirSync(path.join(SITE_DIR, 'product'), { recursive: true });
  fs.mkdirSync(path.join(SITE_DIR, 'css'), { recursive: true });
  // site/products/ already has images; we only generate HTML and CSS

  // Index: gallery grid
  const gridItems = products.map(p => {
    const img = (p.images && p.images[0]) || '';
    const imgUrl = img ? `products/${p.slug}/${img}` : '';
    return `
    <a href="product/${p.slug}.html" class="product-card">
      ${imgUrl ? `<img src="${imgUrl}" alt="${escapeHtml(p.title)}" loading="lazy">` : '<div class="no-img">No image</div>'}
      <span class="product-title">${escapeHtml(p.title)}</span>
      ${p.price ? `<span class="product-price">€${p.price}</span>` : ''}
    </a>`;
  }).join('');

  const indexBody = `
  <section class="intro">
    <h1>Art Supreme</h1>
    <p>World's first AI gallery. Unique artworks generated by artificial neural networks.</p>
  </section>
  <section class="gallery grid">
    ${gridItems}
  </section>`;

  fs.writeFileSync(
    path.join(SITE_DIR, 'index.html'),
    layout('Gallery', indexBody, 'home', ''),
    'utf8'
  );

  // Product pages
  for (const p of products) {
    const images = (p.images || []).slice().sort();
    const imgTags = images.map((f, i) =>
      `<img src="../products/${p.slug}/${f}" alt="${escapeHtml(p.title)} ${i + 1}"${i === 0 ? ' class="main"' : ''} loading="${i === 0 ? 'eager' : 'lazy'}">`
    ).join('\n    ');
    const galleryHtml = images.length > 0
      ? `<div class="product-gallery">${imgTags}</div>`
      : '';
    const buyBtn = p.stripePaymentLinkUrl
      ? `<a href="${escapeHtml(p.stripePaymentLinkUrl)}" class="btn btn-buy" target="_blank" rel="noopener">Buy — €${p.price}</a>`
      : (p.price ? `<p class="price">€${p.price} — <a href="../contact.html">Contact to purchase</a></p>` : '');

    const body = `
  <article class="product-page">
    <a href="../index.html" class="back">← Gallery</a>
    ${galleryHtml}
    <div class="product-info">
      <h1>${escapeHtml(p.title)}</h1>
      ${p.excerpt ? `<p class="excerpt">${escapeHtml(p.excerpt)}</p>` : ''}
      ${p.content ? `<div class="content">${escapeHtml(p.content).replace(/\n/g, '<br>')}</div>` : ''}
      ${buyBtn}
    </div>
  </article>`;

    fs.writeFileSync(
      path.join(SITE_DIR, 'product', p.slug + '.html'),
      layout(p.title, body, '', '../'),
      'utf8'
    );
  }

  // Static pages (placeholders)
  const shippingBody = `
  <article class="page">
    <h1>Shipping & Return</h1>
    <p>We ship worldwide. Flat rate shipping. Contact us for details.</p>
  </article>`;
  fs.writeFileSync(path.join(SITE_DIR, 'shipping.html'), layout('Shipping', shippingBody, 'shipping', ''), 'utf8');

  const contactBody = `
  <article class="page">
    <h1>Contact</h1>
    <p>Email: <a href="mailto:info@art-supreme.com">info@art-supreme.com</a></p>
  </article>`;
  fs.writeFileSync(path.join(SITE_DIR, 'contact.html'), layout('Contact', contactBody, 'contact', ''), 'utf8');

  const successBody = `
  <article class="page page-success">
    <div class="success-icon" aria-hidden="true">✓</div>
    <h1>Thank you for your purchase</h1>
    <p class="success-lead">Your order has been confirmed. We'll get in touch regarding shipping and delivery.</p>
    <p>Questions? <a href="contact.html">Contact us</a>.</p>
    <a href="index.html" class="btn">Back to gallery</a>
  </article>`;
  fs.writeFileSync(path.join(SITE_DIR, 'success.html'), layout('Order confirmed', successBody, '', ''), 'utf8');

  // CSS
  const css = `/* Art Supreme – minimal layout */
* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, sans-serif; line-height: 1.5; color: #222; background: #fafafa; }
.site-header { display: flex; justify-content: space-between; align-items: center; padding: 1rem 2rem; background: #111; color: #fff; }
.site-header a { color: inherit; text-decoration: none; }
.site-header nav a { margin-left: 1.5rem; }
.site-header nav a:hover, .site-header nav a.active { text-decoration: underline; }
.site-main { max-width: 1200px; margin: 0 auto; padding: 2rem; }
.site-footer { text-align: center; padding: 2rem; color: #666; font-size: 0.9rem; }
.intro { text-align: center; margin-bottom: 3rem; }
.intro h1 { font-size: 2rem; margin-bottom: 0.5rem; }
.gallery.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 1.5rem; }
.product-card { display: block; text-decoration: none; color: inherit; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); transition: transform 0.2s; }
.product-card:hover { transform: translateY(-4px); }
.product-card img { width: 100%; height: 260px; object-fit: cover; display: block; }
.product-card .no-img { width: 100%; height: 260px; background: #eee; display: flex; align-items: center; justify-content: center; color: #999; }
.product-card .product-title { display: block; padding: 0.75rem 1rem; font-weight: 600; }
.product-card .product-price { display: block; padding: 0 1rem 0.75rem; color: #666; font-size: 0.9rem; }
.product-page { display: grid; gap: 2rem; }
@media (min-width: 768px) { .product-page { grid-template-columns: 1fr 1fr; } }
.product-gallery { display: flex; flex-direction: column; gap: 0.5rem; }
.product-gallery img { width: 100%; height: auto; border-radius: 8px; }
.product-gallery img.main { order: -1; }
.product-info h1 { margin-top: 0; }
.product-info .excerpt { color: #555; }
.product-info .content { margin: 1rem 0; }
.btn { display: inline-block; padding: 0.75rem 1.5rem; background: #111; color: #fff; text-decoration: none; border-radius: 6px; margin-top: 1rem; }
.btn:hover { background: #333; }
.back { display: inline-block; margin-bottom: 1rem; color: #666; text-decoration: none; }
.back:hover { color: #111; }
.page h1 { margin-top: 0; }
.page-success { text-align: center; padding: 3rem 2rem; }
.page-success .success-icon { width: 4rem; height: 4rem; margin: 0 auto 1.5rem; background: #1a7f37; color: #fff; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 2rem; font-weight: bold; line-height: 1; }
.page-success h1 { font-size: 1.75rem; margin-bottom: 0.75rem; }
.page-success .success-lead { font-size: 1.1rem; color: #444; margin-bottom: 1.5rem; }
.page-success .btn { margin-top: 1rem; }
`;

  fs.writeFileSync(path.join(SITE_DIR, 'css', 'style.css'), css, 'utf8');

  console.log('Built site to', SITE_DIR);
}

build();
